services:
  postgres:
    container_name: tasks_postgres
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=tasks_db'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    ports:
      - 5432:5432
